FROM node:12 AS builder

WORKDIR /usr/src/app

# Install node modules
COPY package*.json ./
RUN npm install

# Build the app
COPY . .
RUN npm run build


FROM node:12-alpine AS runner

WORKDIR /usr/src/app

# Copy app
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package*.json ./

# Run command
CMD [ "node", "dist/main.js" ]
