version: '3'

services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./storage/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - domain4632-network

  domain4632-api:
    container_name: domain4632-api
    image: node:12
    volumes:
      - .:/usr/src/app
    networks:
      - domain4632-network
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    command: npm run start:dev

  domain4632-db:
    container_name: domain4632-db
    image: mongo:latest
    volumes:
      - ./storage/db:/data/db
    ports:
      - 27017:27017
    networks:
      - domain4632-network

networks:
  domain4632-network:
