version: '3'

services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./storage/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./storage/certbot/conf:/etc/letsencrypt:ro
      - ./storage/certbot/www:/var/www/certbot:ro
    ports:
      - 80:80
    networks:
      - domain4632-network
    restart: always

  domain4632-api:
    container_name: domain4632-api
    build: .
    networks:
      - domain4632-network
    restart: always

  domain4632-db:
    container_name: domain4632-db
    image: mongo:latest
    volumes:
      - ./storage/db:/data/db:rw
    ports:
      - 27017:27017
    networks:
      - domain4632-network
    restart: always
  
  # certbot:
    # image: certbot/certbot
    # container_name: certbot
    # volumes: 
    #   - ./storage/certbot/conf:/etc/letsencrypt:rw
    #   - ./storage/certbot/www:/var/www/certbot:rw
    # command: certonly --webroot -w /var/www/certbot --force-renewal --email ${EMAIL} -d ${DOMAIN} --agree-tos

networks:
  domain4632-network:
